---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shuangjun Liu.
--- DateTime: 5/18/2018 7:38 PM
---
--- this is for multiple prediction evaluation tasks.
require 'paths'
require 'hdf5'
require 'os'
paths.dofile('util/eval.lua')    -- equals eval in train
paths.dofile('util/img.lua')
paths.dofile('ref.lua')        -- ds information

-- for AR computer
--local exFd= '/home/jun/exp/pose-hg-train'   -- exFd   set from opt
--local exFd = '/home/jun/SDrive/rst_model/pose-hg-train/eval'
--local dsNm = 'AC2d'     -- dsNm
--local dsNm = 'MPI'    -- use opt to set this one

-- choose the right suffix to plot
--local angSfx = '_45'
local angSfx = ''
local tsLs = {
    --'RR_P7_15_A00_ts1' .. angSfx,
    --'RR_P7_15_A00_wns_ts1' .. angSfx,
    --'RR_P7_15_A00_gauFt_ts1' .. angSfx .. '_gauFt',
    --'RR_P7_15_A00_lap_ts1' .. angSfx .. '_lap',
    --'SURREAL_10000_ts1' .. angSfx,
    --'SURREAL_10000_wns_ts1' .. angSfx,
    --'SURREAL_10000_gauFt_ts1' .. angSfx .. '_gauFt',
    --'umich-stacked-hourglass_ts1' .. angSfx
    --'umich-stacked-hourglass_GPM_MPI'
}

local legends = {
    --'mocapScan',
    --'mocapScan-wns',
    --'mocapScan-gauss',
    --'mocapScan-lap',
    --'SURREAL',
    --'SURREAL-wns',
    --'SURREAL-gauFt',
    --'hg-Pretrained'
    --'hg-GPM-MPI'
}
local dists = {}
local ifSvIm = true
--local evalFd = '/home/jun/exp/pose-hg-train/eval'
local evalFd = '/home/jun/SDrive/rst_model/pose-hg-train/eval'
os.execute('mkdir -p ' .. evalFd)   -- try safely make dir
--local evalNm = 'state_of_art'
local evalNm = 'GPM_ds'
local evalSpecFd
if ifSvIm then
    evalSpecFd = paths.concat(evalFd, evalNm)
    os.execute('mkdir -p ' .. evalSpecFd)
else
    evalSpecFd = nil
end


for i = 1, #tsLs  do
    local predPth = paths.concat(opt.expDir,opt.dataset,tsLs[i],'final_preds.h5')
    local predFile = hdf5.open(predPth)
    --print(predFile)
    local preds = predFile:read('preds'):all()
    --local joints_gt = predFile:read('joints_gt'):all()
    local lenTorsos = predFile:read('lenTorsos'):all()
    local idxs = predFile:read('idxs'):all()
    --print('idx 20 is', idxs:sub(1,20))
    --print('idxs max and min are', idxs:max(), idxs:min())
    --print('idxs size is', idxs:size())
    --print('the joints gt size is', dataset.joints_gt:size())
    --print('current index i is', i)
    local joints_gt = dataset.joints_gt:index(1,idxs:long()):clone()   -- this one only works for
    --print('joints_gt size is', joints_gt:size())
    --print('size of data is', preds:size(),joints_gt:size(), lenTorsos:size())
    -- 83 x16 x 5 for preds cut first 2
    --print('the index is', idxs)
    --print('joints_gt is', )
    table.insert(dists,calcDists(preds:narrow(3,1,2),joints_gt,lenTorsos))
    -- 16 x N

end

require 'gnuplot'
--gnuplot.raw('set terminal postscript noenhanced')
gnuplot.figure(1)
gnuplot.raw('set bmargin 1')
gnuplot.raw('set lmargin 3.2')
gnuplot.raw('set rmargin 2')

gnuplot.raw('set multiplot layout 2,3 title "AClab 2d PCK"')
gnuplot.raw('set xtics font ",6"')
gnuplot.raw('set ytics font ",6"')
displayPCK(dists, {9,10}, legends, 'Head',evalSpecFd, true)   -- show key means the legend,  multiple plot, how to change subplot?
displayPCK(dists, {2,5}, legends, 'Knee',evalSpecFd)
displayPCK(dists, {1,6}, legends, 'Ankle',evalSpecFd)
gnuplot.raw('set tmargin 2.5')
gnuplot.raw('set bmargin 1.5')
displayPCK(dists, {13,14}, legends, 'Shoulder',evalSpecFd)
displayPCK(dists, {11,16}, legends, 'Wrist',evalSpecFd)
displayPCK(dists, {12,15}, legends, 'Elbow', evalSpecFd)
gnuplot.raw('unset multiplot')

gnuplot.figure(2)
displayPCK(dists,{1,2,5,6,9,10,11,12,13,14,15,16},legends,'total',evalSpecFd,true)

