---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shuangjun Liu.
--- DateTime: 5/18/2018 7:38 PM
---
--- this is for multiple prediction evaluation tasks. It perform cross dataset evaluation
--- the ds list follow format <DS_nm>/<expID>
require 'paths'
require 'hdf5'
require 'os'
paths.dofile('util/eval.lua')    -- equals eval in train
paths.dofile('util/img.lua')
paths.dofile('ref.lua')        -- ds information


-- for sim all cover with RGB cover cases full network training
opt.evalNm = 'simLab_covs_full'      -- show performance over cover conditions
local tsLs = {
    'datasetPM/simLab/cov-u12_cov-u',
    'datasetPM/simLab/cov-u12_cov-1',
    'datasetPM/simLab/cov-u12_cov-2',
    'datasetPM/simLab/cov-u12_cov-u12',
    'datasetPM/simLab/umich-stacked-hourglass_covRGB-u',
    'datasetPM/simLab/umich-stacked-hourglass_covRGB-1',
    'datasetPM/simLab/umich-stacked-hourglass_covRGB-2',
    'datasetPM/simLab/umich-stacked-hourglass_covRGB-u12',
    'datasetPM/simLab/umich-stacked-hourglass_cov-u12',
}
local legends = {
    'hg(UCITD)-uncover',
    'hg(UCITD)-cover1',
    'hg(UCITD)-cover2',
    'hg(UCITD)-allCover',
    'hg-RGBuncover',
    'hg-RGBcover1',
    'hg-RGBcover2',
    'hg-RGB',
    'hg-LWIR',
    }

-- dana all cover cases *********************
--opt.evalNm = 'danaLab_covs_ftLast'      -- show performance over cover conditions
--local tsLs = {
--    'datasetPM/danaLab/umich-stacked-hourglass-ftLast--cov-u12_cov-u',
--    'datasetPM/danaLab/umich-stacked-hourglass-ftLast--cov-u12_cov-1',
--    'datasetPM/danaLab/umich-stacked-hourglass-ftLast--cov-u12_cov-2',
--    'datasetPM/danaLab/umich-stacked-hourglass-ftLast--cov-u12_cov-u12',
--    'datasetPM/danaLab/umich-stacked-hourglass_covRGB-u',
--    'datasetPM/danaLab/umich-stacked-hourglass_covRGB-1',
--    'datasetPM/danaLab/umich-stacked-hourglass_covRGB-2',
--    'datasetPM/danaLab/umich-stacked-hourglass_covRGB-u12',
--    'datasetPM/danaLab/umich-stacked-hourglass_cov-u12',
--}
--
--local legends = {
--    'hg(UCITD)-uncover',
--    'hg(UCITD)-cover1',
--    'hg(UCITD)-cover2',
--    'hg(UCITD)-allCover',
--    'hg-RGBuncover',
--    'hg-RGBcover1',
--    'hg-RGBcover2',
--    'hg-RGB',
--    'hg-LWIR',
--    }

local dists = {}
local ifSvIm = true     -- save plot
--local evalFd = '/home/jun/exp/pose-hg-train/eval'
local evalFd = '/home/jun/SDrive/rst_model/pose-hg-train/eval'
os.execute('mkdir -p ' .. evalFd)   -- try safely make dir
--local evalNm = 'state_of_art'
--local evalNm = 'GPM_ds_100'
--local evalNm = opt.evalNm
local evalSpecFd
if ifSvIm then
    evalSpecFd = paths.concat(evalFd, opt.evalNm)
    os.execute('mkdir -p ' .. evalSpecFd)
else
    evalSpecFd = nil
end


for i = 1, #tsLs  do
    local predPth = paths.concat(opt.expDir,tsLs[i],'final_preds.h5')
    local predFile = hdf5.open(predPth)
    --print(predFile)
    -- DB, list all the fields
    --print('the content in the hdf5 file is')
    --for k,v in pairs(predFile:all()) do print(k,'\n') end
    local preds = predFile:read('preds'):all()
    --local joints_gt = predFile:read('joints_gt'):all()
    local lenTorsos = predFile:read('lenTorsos'):all()
    local idxs = predFile:read('idxs'):all()
    local joints_gt = predFile:read('joints_gt'):all()  -- jonits_gt already in there?
    table.insert(dists,calcDists(preds:narrow(3,1,2),joints_gt,lenTorsos))
    -- 16 x N
end

require 'gnuplot'
--gnuplot.raw('set terminal postscript noenhanced')
gnuplot.figure(1)
gnuplot.raw('set bmargin 1')
gnuplot.raw('set lmargin 3.2')
gnuplot.raw('set rmargin 2')

gnuplot.raw('set multiplot layout 2,3 title "AClab 2d PCK"')
gnuplot.raw('set xtics font ",6"')
gnuplot.raw('set ytics font ",6"')
displayPCK(dists, {9,10}, legends, 'Head',evalSpecFd, true, 4)   -- show key means the legend,  multiple plot, how to change subplot?
displayPCK(dists, {2,5}, legends, 'Knee',evalSpecFd, false, 4)
displayPCK(dists, {1,6}, legends, 'Ankle',evalSpecFd, false, 4)
gnuplot.raw('set tmargin 2.5')
gnuplot.raw('set bmargin 1.5')
displayPCK(dists, {13,14}, legends, 'Shoulder',evalSpecFd, false, 4)
displayPCK(dists, {11,16}, legends, 'Wrist',evalSpecFd, false, 4)
displayPCK(dists, {12,15}, legends, 'Elbow', evalSpecFd, false, 4)
gnuplot.raw('unset multiplot')

gnuplot.figure(2)
displayPCK(dists,{1,2,5,6,9,10,11,12,13,14,15,16},legends,'total',evalSpecFd,true,4 )

