---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shuangjun Liu.
--- DateTime: 5/10/2018 9:10 PM
---
matio = require 'matio'
require 'pl'
local dsFd = '/home/jun/datasets/datasetPM/simLab'
local idx_sub = 1
--local subjFd = path.join(dsFd, string.format('%05d',idx_sub))
local subjFd = path.join(dsFd, ('%05d'):format(idx_sub))
--print('subj fd is', subjFd)

----------------------- pure basic operation -------------
--local matPth ='/home/jun/datasets/SYN/SYN_RR_sarah_180423_1317_G20180508_2250_P2000_A00/'
--local joints_gt_tmp = matio.load(paths.concat(matPth,'joints_gt.mat'),'joints_gt')
--print(joints_gt_tmp:sub(1,2))
--
--local tb1 = {'haha','baba','lala'}
--local tb2 = table.unpack(tb1,1,2)
--print('tb2', tb2)
--
--local lin1 = torch.linspace(10,100,10)  -- 10,20.... 100
--print(lin1)
--
--str1 = 'haha\\_wawa' -- \_ doesn't exist, we need double \\ interpret in latex in other format
----str2 = str1
----str2 = 'nanana'     -- open a new memory
--print(str1)
--local a = 1/0
--local b = a + 1
--print('a is', a)    -- rst inf
--print(b)
--local scl1 = 1
--if scl1= 2 then       --  equal can't pass the logic
--    print('equal pass in as logical successfully')
--end
--local ts1 = torch.Tensor(5,5)
--print('ts1 type is', type(ts1))

--local str1 = 'wodema_sjl'
--if str1:match('sjlh') then
--    print('sjl found in str1')
--else
--    print('nothing found')
--end
-- find the index number
--local fNm  = 'image_000001.png'
--local subStr = fNm:match('%d%d%d%d%d%d')    -- 6 number should be unique
--print(subStr)
--print(1 == tonumber(subStr))  -- no equal? how to change 000001 to 1
--local str1 = ''
--if str1 ==' ' then      -- empty string will pass the check, space is different from the empty
--    print('empty pass if yes')
--else
--    print('string is nothing')
--end
--local tb1 = {4,5,6}
--print(tb1[#tb1])
print('haha', 1,'bushi ')   -- worked combined information

--- function test----
--local a = 9
--local function moda(a)
--    a = a+1 -- will not change a
--end
--print(a)

----- test the dir funcs  -----
--local rtLs = dir.getfiles(subjFd)
--for i, fNm in ipairs(rtLs) do
--    print(fNm)
--end

