--- Generate PCK from all test results, then use step to segment to show PCK all for each subj
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shuangjun Liu.
--- DateTime: 3/25/2019 4:42 PM
---

paths.dofile('ref.lua')        -- ds information img , eval inside there

local tsFd
--tsFd = 'datasetPM/simLab/cov-u12_cov-u12'
tsFd = 'SLP/danaLab/cov-u12_cov-u12'
local tsLs = {tsFd}
local step = 135

local dists = {}
local ifSvIm = true
local evalFd = '/home/jun/SDrive/rst_model/pose-hg-train/eval'
os.execute('mkdir -p ' .. evalFd)   -- try safely make dir

local predPth = paths.concat(opt.expDir,tsFd,'final_preds.h5')
local predFile = hdf5.open(predPth)
local preds = predFile:read('preds'):all()      -- transferred, then scored
--local joints_gt = predFile:read('joints_gt'):all()
local lenTorsos = predFile:read('lenTorsos'):all()
local idxs = predFile:read('idxs'):all()
local joints_gt = predFile:read('joints_gt'):all()  -- jonits_gt already in there?
--table.insert(dists,calcDists(preds:narrow(3,1,2),joints_gt,lenTorsos))
local dist_smpls_comb = calcDists(preds:narrow(3,1,2),joints_gt,lenTorsos)   --  n_jt x n_bch
print('size of the dist_smpls', dist_smpls_comb:size())
-- get the subj list
local PCK_subjs = {}
local n_subj = math.floor(dist_smpls_comb:size(2)/step)
-- get comparison joints only
dist_smpls_comb = dist_smpls_comb:index(1, torch.LongTensor{1,2,5,6,9,10,11,12,13,14,15,16})

--print('there is subj', n_subj)
for i = 1,n_subj do
    local dist_subj = dist_smpls_comb:narrow(2, step*(i-1)+1, step)
    local PCK_subj = {}
    for j = 1, 5 do  -- 5 resolutions
        table.insert(PCK_subj, distAccuracy(dist_subj, 0.1*j))
    end
    --print('current PCK subj is', PCK_subj)
    table.insert(PCK_subjs, PCK_subj)
end
local PCK_total ={}
for j = 1,5 do
    table.insert(PCK_total, distAccuracy(dist_smpls_comb, 0.1*j))
end

print('PCK result for different subject is')
for idx, pck in ipairs(PCK_subjs) do
    print('idx:', idx, 'pck0.1:', pck[1], 'pck0.2', pck[2])
end
print('total PCK(0.1~0.5) is', PCK_total)